<Project>

  <PropertyGroup>
    <_StaticHostRid></_StaticHostRid>
    <_StaticHostRid Condition="'$(_StaticHostRid)' == '' and '$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</_StaticHostRid>
    <_StaticHostRid Condition="'$(_StaticHostRid)' == '' and '$(AppHostRuntimeIdentifier)' != ''">$(AppHostRuntimeIdentifier)</_StaticHostRid>
    <_StaticHostRid Condition="'$(_StaticHostRid)' == '' and '$(DefaultAppHostRuntimeIdentifier)' != ''">$(DefaultAppHostRuntimeIdentifier)</_StaticHostRid>
    <_StaticNativeArch Condition="'$(_StaticHostRid)' == 'win-arm64'">arm64</_StaticNativeArch>
    <_StaticNativeArch Condition="'$(_StaticNativeArch)' == ''">x64</_StaticNativeArch>
    <_NativeLibsDir>$(MSBuildThisFileDirectory)../build/native/$(_StaticNativeArch)/</_NativeLibsDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(_StaticHostRid)' == 'win-x64' or '$(_StaticHostRid)' == 'win-arm64' or '$(_StaticHostRid)' == 'linux-x64'">
    <DirectPInvoke Include="libHarfBuzzSharp" />
    <DirectPInvoke Include="libSkiaSharp" />
  </ItemGroup>

  <ItemGroup Condition="'$(_StaticHostRid)' == 'win-x64' or '$(_StaticHostRid)' == 'win-arm64'">
    <NativeLibrary Include="$(_NativeLibsDir)/*.lib" />
    <NativeLibrary Update="$(_NativeLibsDir)libHarfBuzzSharp.lib">
     <WholeArchive>true</WholeArchive>
    </NativeLibrary>
    <NativeLibrary Update="$(_NativeLibsDir)SkiaSharp.lib">
     <WholeArchive>true</WholeArchive>
    </NativeLibrary>
    <LinkerArg Include="FontSub.lib;opengl32.lib;advapi32.lib;gdi32.lib" />
  </ItemGroup>

  <ItemGroup Condition="'$(_StaticHostRid)' == 'linux-x64'">
    <NativeLibrary Include="$(_NativeLibsDir)/*.a" />
    <NativeLibrary Update="$(_NativeLibsDir)libHarfBuzzSharp.a">
      <WholeArchive>true</WholeArchive>
    </NativeLibrary>
    <NativeLibrary Update="$(_NativeLibsDir)libSkiaSharp.a">
      <WholeArchive>true</WholeArchive>
    </NativeLibrary>
    <LinkerArg Include="-lfontconfig;-lstdc++" />
  </ItemGroup>

</Project>
