<Project>
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <DefaultRid>win-x64</DefaultRid>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <StaticAppHostPackageVersion>0.2.2</StaticAppHostPackageVersion>
    <AvaloniaAppHostPackageVersion>0.1.0</AvaloniaAppHostPackageVersion>
    <AvaloniaVersion>11.3.12</AvaloniaVersion>

    <StaticAppHostPackageOutputDir>$(RepoRoot)src\package-static-apphost\bin\$(Configuration)</StaticAppHostPackageOutputDir>
    <AvaloniaAppHostPackageOutputDir>$(RepoRoot)src\package-avalonia-apphost\bin\$(Configuration)</AvaloniaAppHostPackageOutputDir>

    <HostLibsRoot>$(RepoRoot)artifacts\hostlibs</HostLibsRoot>
    <AvaloniaNativeLibsRoot>$(RepoRoot)artifacts\skiasharp-2.88.9</AvaloniaNativeLibsRoot>
  </PropertyGroup>
</Project>
