<Project>
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <AvaloniaAppHostPackageVersion>11.0.0-preview.2</AvaloniaAppHostPackageVersion>
    <AvaloniaVersion>11.3.12</AvaloniaVersion>

    <PackagesOutputRoot>$(RepoRoot)artifacts\packages</PackagesOutputRoot>
    <AvaloniaAppHostPackageOutputDir>$(PackagesOutputRoot)\$(Configuration)</AvaloniaAppHostPackageOutputDir>

    <HostLibsRoot>$(RepoRoot)artifacts\hostlibs</HostLibsRoot>
    <AvaloniaNativeLibsRoot>$(RepoRoot)artifacts\skiasharp-2.88.9</AvaloniaNativeLibsRoot>
  </PropertyGroup>
</Project>
