<Project>

  <PropertyGroup>
    <TargetAvaloniaVersion Condition="'$(TargetAvaloniaVersion)' == ''">11.0</TargetAvaloniaVersion>
    <AvaloniaAppHostPackageVersionMajor>0</AvaloniaAppHostPackageVersionMajor>
    <AvaloniaAppHostPackageVersionPrev>preview.4</AvaloniaAppHostPackageVersionPrev>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(TargetAvaloniaVersion)' == '11.0'">
      <PropertyGroup>
        <AvaloniaVersion>11.3.12</AvaloniaVersion>
        <SkiaSharpVersion>2.88.9</SkiaSharpVersion>
        <HarfBuzzVersion>7.3.0</HarfBuzzVersion>
      </PropertyGroup>
    </When>
    <When Condition="'$(TargetAvaloniaVersion)' == '12.0'">
      <PropertyGroup>
        <AvaloniaVersion>12.0.0-preview2</AvaloniaVersion>
        <SkiaSharpVersion>3.119.2</SkiaSharpVersion>
        <HarfBuzzVersion>8.3.1.1</HarfBuzzVersion>
      </PropertyGroup>
    </When>
  </Choose>

  <PropertyGroup>
    <AvaloniaAppHostPackageVersionMeta>skiasharp-v$(SkiaSharpVersion)-harfbuzz-v$(HarfBuzzVersion)</AvaloniaAppHostPackageVersionMeta>

    <AvaloniaAppHostPackageVersion>$(TargetAvaloniaVersion).$(AvaloniaAppHostPackageVersionMajor)</AvaloniaAppHostPackageVersion>
    <AvaloniaAppHostPackageVersion Condition="'$(AvaloniaAppHostPackageVersionPrev)' != ''">$(AvaloniaAppHostPackageVersion)-$(AvaloniaAppHostPackageVersionPrev)</AvaloniaAppHostPackageVersion>
    <AvaloniaAppHostPackageVersion>$(AvaloniaAppHostPackageVersion)+$(AvaloniaAppHostPackageVersionMeta)</AvaloniaAppHostPackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <HostLibsVersion>10.0</HostLibsVersion>
    <HostLibsFlavor Condition="'$(HostLibsFlavor)' == ''">default</HostLibsFlavor>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <PackagesOutputRoot>$([MSBuild]::NormalizePath('$(RepoRoot)', 'artifacts/packages'))</PackagesOutputRoot>
    <AvaloniaAppHostPackageOutputDir>$([MSBuild]::NormalizePath('$(PackagesOutputRoot)', '$(Configuration)'))</AvaloniaAppHostPackageOutputDir>

    <HostLibsBaseRoot>$([MSBuild]::NormalizePath('$(RepoRoot)', 'artifacts/hostlibs/$(HostLibsVersion)'))</HostLibsBaseRoot>
    <HostLibsRoot>$([MSBuild]::NormalizePath('$(HostLibsBaseRoot)', '$(HostLibsFlavor)'))</HostLibsRoot>
    <AvaloniaNativeLibsRoot>$([MSBuild]::NormalizePath('$(RepoRoot)', 'artifacts/skiasharp/$(SkiaSharpVersion)'))</AvaloniaNativeLibsRoot>
  </PropertyGroup>

</Project>
