target_os = "win"
target_cpu = "x64"
skia_enable_fontmgr_win_gdi = false
skia_use_dng_sdk = true
skia_use_icu = false
skia_use_piex = true
skia_use_sfntly = false
skia_use_system_expat = false
skia_use_system_libjpeg_turbo = false
skia_use_system_libpng = false
skia_use_system_libwebp = false
skia_use_system_zlib = false
skia_enable_skottie = true
is_static_skiasharp = true
skia_use_vulkan = true
clang_win = "C:/Program Files/LLVM"
win_vcvars_version = "14.5"
extra_cflags = [
  "-DSKIA_C_DLL",
  "/MT",
  "/EHsc",
  "/Z7",
  "-D_HAS_AUTO_PTR_ETC=1",
  "/arch:AVX2",
  "-D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS=1",
]
extra_ldflags = [
  "/DEBUG:FULL",
  "/DEBUGTYPE:CV,FIXUP",
]
skia_enable_tools = false
is_official_build = true
