<Project>
  <ItemGroup>
    <HostForgeStaticPackage Include="$(MSBuildThisFileName)">
      <Component>Angle</Component>
      <Rid>$([System.String]::Copy('$(MSBuildThisFileName)').Replace('ChsBuffer.Angle.Static.', ''))</Rid>
      <NativeDir>$(MSBuildThisFileDirectory)../build/native/$([System.String]::Copy('$(MSBuildThisFileName)').Replace('ChsBuffer.Angle.Static.', ''))</NativeDir>
    </HostForgeStaticPackage>
  </ItemGroup>
</Project>
