<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <PropertyGroup>
    <StaticHostAssetsBaseDir>$(HostLibsRoot)</StaticHostAssetsBaseDir>
  </PropertyGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <Import Project="$(MSBuildProjectDirectory)\..\..\src\StaticAppHost.targets" />

  <PropertyGroup>
    <RidOrDefault>$(RuntimeIdentifier)</RidOrDefault>
    <RidOrDefault Condition="'$(RidOrDefault)' == ''">$(DefaultAppHostRuntimeIdentifier)</RidOrDefault>
  </PropertyGroup>

  <ItemGroup>
    <NativeLibrary Include="$(MSBuildProjectDirectory)\NativeLib\dll.lib" Condition="$(RidOrDefault.StartsWith('win'))">
      <WholeArchive>true</WholeArchive>
    </NativeLibrary>
    <NativeLibrary Include="$(MSBuildProjectDirectory)\NativeLib\dll.a" Condition="!$(RidOrDefault.StartsWith('win'))">
      <WholeArchive>true</WholeArchive>
    </NativeLibrary>
  </ItemGroup>

  <Target Name="BuildNativeLib" BeforeTargets="CoreCompile">
    <Exec Command="python build.py"
          WorkingDirectory="$(ProjectDir)NativeLib" />
  </Target>

</Project>
